[package]
name = "slidmk"
version = "0.1.0"
authors = ["generic <genericgithub@tutanota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utf8-chars = "1.0.2"
printpdf = "0.3.2"
