[package]
name = "slidmk"
version = "0.1.0"
authors = ["generic <genericgithub@tutanota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# utf8-chars = "1.0.2"
regex = "1.5.4"
lazy_static = "1.4.0"
